- README.md
- src/echo-server.ts
This patch allows to use official SSL certificates.
> Allow to use SSL

- src/server.ts
When checking for which http protocol to use, the "host" option in the json file is tested to see if it starts with `https` or `http`
However, if the host option DOES start with either of those, the script throws a `Error: getaddrinfo ENOTFOUND` error. See [tech info here](http://stackoverflow.com/a/17691556/659786).
So removing the protocol from the `host` options means we must use something else to check for http(s). This patch uses the `protocol` option in the json file. First suggested by https://github.com/Thaars
> Fix checking for http via host option.

- package.json
Running `npm run compile watch` didn't work, would result in running `tsc watch` not `tsc -w`
> fix compile watch script

- src/subscribers/redis-subscriber.ts
Hello!
I've been trying to integrate this with a new project, and I was/am having difficulty receiving events on the frontend that have namespaces that reach further than the traditional "App\Events\{ClassName}".
I.e. I'm having issues receiving an event with a namespace of "App\Events\{AddedNamespaceLevel}\{OtherNamespaceLevel}\{ClassName}".
I wanted to check if the actual event had been sent, but had to dig into the code to get this confirmation.
I think this addition would be helpful to other developers, and I hope you will accept this change. (My first public contribution!)
Thanks.
> Add More DevMode Visibility

- src/database/sqlite.ts
If the database already exist, it fails on re-creating the index. This should fix this. Fixes issue #41.
> Only create sqlite index if not exists

- src/channels/private-channel.ts
This adds extra error handling to the authentication process.
- Fix typo in ServerRequest
- Difference between error (eg. invalid url) or invalid response (eg. not authenticated or error 500)
- Show authentication message in dev mode for succes + fail
- Show response when unauthenticated, to see what is wrong (eg. internal error or ..)
> Clear error messages for authenticating

- README.md
- package.json
https://github.com/uWebSockets/uWebSockets claims to be a lot faster then the default 'ws' websocket implementation. It's possible to replace this, but I think we need to add it as a dependency to be able to use it directly.  It's added as optional dependency so it should not fail if it can't install it (don't know why it should), based on https://github.com/socketio/engine.io/pull/459
It should be the default in engine.io v2, but not sure how long that's away :)
> Add uws as optional dependancy

- src/channels/channel.ts
- src/channels/private-channel.ts
On subscription errors, emit an event with the status code.
```js
channel.on('subscription_error', function(status){
alert('Error: ' + status );
})
```
Can be used to show an error message, refresh the page etc. Fixes #91
> Emit subscription errors

- src/echo-server.ts
Otherwise this gets removed after adding an option (eg. client:add)
> Add missing protocol option

- package.json
A new major version of socket.io has been released, together with the engine/parser etc.
uws is included by default now.
See https://github.com/socketio/socket.io/releases/tag/2.0.0
https://github.com/socketio/socket.io-client/releases
But I'm not sure if there is anything breaking, and if 2.x is compatible with 2.x clients only..
> [Needs testing] Bump socket.io

- src/channels/private-channel.ts
As described in #185 allow for wildcard domain declaration in authHost option (e.g. authHost = '.myapp.com') so one use the laravel-echo-server with a multi tenant/subdomain system. The currently appropriate domain is retrived from the referer and matched with the wildcard domain declaration (if a wildcard is used). @tlaverdure please check. Thanks!
**Updated version**
See comments below...
> Allow wildcard and multi domain authHost option

- src/channels/private-channel.ts
When request connection from apps that doesn't send referer header, the server crash.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer
Should fix #197 
I don't know if is the best way choose the first auth host (if it is an array).
> Added validation if the socket doesn't have the referer header.

- README.md
- src/api/http-api.ts
- src/cli/cli.ts
- src/echo-server.ts
Added a fix to allow AJAX calls to ping the API from either same domain different port, or totally different domain. CORS settings are set from laravel-echo-server.json file. Ran into a situation where I needed this and fixed it manually but that's not a long term fix, so I decided to make a fork and pull request with this feature.
Thank you for looking into and hopefully integrating it with the system. 
Thanks!
> Define Cross Domain Allow Headers To Be Set For The API

- README.md
- package.json
- src/echo-server.ts
This seeks to address the issue that was raised in https://github.com/tlaverdure/laravel-echo-server/issues/178.
It's a problem I was having tonight when trying to deploy a project using `laravel-echo-server` to a staging environment and off of my local for the first time.
In the solution below I decided to take the middle path between simple and configurable allowing for a bit of configuration without too much overhead.
Should you believe that this is a good approach, any suggestions or requests to adapt the code are welcome.
> Allow loading of default Laravel .env vars

- .gitignore
- README.md
- package-lock.json
- src/database/redis.ts
With this PR you can publish updates on presence channels to redis. This way your Laravel app can be triggered and informed about updated presence channel states, without querying laravel-echo-server's persistence layer.
The gained possibilities resemble those of Pusher's [presence related webhooks](https://pusher.com/docs/webhooks#presence), only sleeker by using Pub/Sub.
The readme has been updated accordingly.
I'd really like to see this in the official release. Thanks for the great project!
> Publish presence channel updates

- src/server.ts
Encountered an issue specifically in OpenShift where the port number that is read from the "options" is returned as "tcp://x.x.x.x:6001" instead of just "6001". This does not happen in Docker, only OpenShift. 
I added a RegEx to parse the actual port number out of the "this.options.port". For most users, this will have no effect as it will still return the port number. But if a full tcp string is given, it will grab just the port number and bind to it. This was causing issues when attempting to .listen().
> Updated port value to address issue with OpenShift

- README.md
The new `subscribers` option added in #333 as well as the old `devMode` option were missing from the documentation. This PR also reworks the environment variable documentation slightly, so that it is clear what is meant.
I also moved one option to sort the configuration options alphabetically.
> Add missing documentation for some options to readme

- src/api/http-api.ts
This adds a simple route to the HTTP API.
`GET /` now returns an 'OK' message with a 200 response code (or 304).
This is so a client-side library can check that the echo server is running before attempting to connect.
Currently the only option is to wait for a WebSocket to fail if the server is not running, or try and make an HTTP request against one of the existing URLs, which will only return a successful response code if you supply the correct [client credentials](https://github.com/tlaverdure/laravel-echo-server#api-clients). We don't want to do that because then the other HTTP endpoints would be available to reveal information about the server.
Adding the simple `/` route allows an HTTP request that will return a HTTP 200.
> Add simple index route for HTTP API.

- README.md
- src/cli/cli.ts
It's a good practice to use password for redis connections and most of the projects already handle all the things in different environments in env file. So it would be handy to be able to set password in .env
> Add redis password to allowed env variables

- src/echo-server.ts
This disables TLS 1.0 to be disabled by default. To allow TLS 1.0, you can override this option with an empty string.
> By default insecure TLS v1 is now disabled

- src/server.ts
This code will allow custom HTTP headers to be specified in the laravel-echo-server.json configuration so that they are added to every HTTP response. This is needed for PCI-DSS compliance. For example this would allow the following required headers for PCI-DSS to be set:
"headers" : {
"X-XSS-Protection": "1;mode=block",
"X-Content-Type-Options": "nosniff",
"Strict-Transport-Security": "max-age=31536000"
},
> Allow custom headers to be added to HTTP response

- README.md
Kinda a bummer. I wish it could be absolute or relative depending on the opening string, but if it's done it will break many Echo installations.
> Added note about SQLite path being relative.

- README.md
- src/subscribers/redis-subscriber.ts
We need to use a prefix in our laravel redis connection and therefore the laravel-echo-server needs to acknowledge this prefix as well.
I used the same option referenced in [this comment](https://github.com/tlaverdure/laravel-echo-server/pull/438#issuecomment-554062994)
> #400 KeyPrefix for redis

- examples/server_stop.js
- src/echo-server.ts
- src/subscribers/http-subscriber.ts
- src/subscribers/redis-subscriber.ts
- src/subscribers/subscriber.ts
Added a method to stop the running echo server.
When the server is stopped Redis subscriber is disconnected, the http-subscriber endpoint is changed to 404 and the socket.io server is closed.
> Add method to stop the running server

- src/channels/private-channel.ts
In my production environment the echo server crashed regularly with the following exception:
```
[3:59:41 PM] - bQMwq6OeDT4g3BddAAau joined channel: footer-stats
/usr/lib/node_modules/laravel-echo-server/dist/channels/private-channel.js:48
return referer.hostname.substr(referer.hostname.indexOf('.')) === host ||
^
TypeError: Cannot read property 'substr' of null
at PrivateChannel.hasMatchingHost (/usr/lib/node_modules/laravel-echo-server/dist/channels/private-channel.js:48:33)
at PrivateChannel.authHost (/usr/lib/node_modules/laravel-echo-server/dist/channels/private-channel.js:35:26)
at PrivateChannel.authenticate (/usr/lib/node_modules/laravel-echo-server/dist/channels/private-channel.js:13:23)
at Channel.joinPrivate (/usr/lib/node_modules/laravel-echo-server/dist/channels/channel.js:68: …
```
> Fix crash when invalid referer is sent
